api_platform:
    title: 'Task Manager API'
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        jsonpatch: ['application/merge-patch+json', 'application/json']
